[package]
name = "safe-box"
version = "0.1.0"
edition = "2021"
authors = ["misaka10987 <misaka10987@outlook.com>"]
description = "Utilities for managing a password database."
documentation = "https://github.com/misaka10987/safe-box"
homepage = "https://github.com/misaka10987/safe-box"
repository = "https://github.com/misaka10987/safe-box"
readme = "README.md"
keywords = ["safe-box", "password", "safety"]
license = "MIT"

[dependencies]
crypto = { version = "0.5.1", features = ["password-hash"] }
argon2 = { version = "0.5.3", optional = true }
scrypt = { version = "0.11.0", optional = true }
sqlite = "0.36.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }

[features]
default = ["argon2"]
